[WIP] Audio-based TN for long text
NVIDIA/NeMo-text-processing pull request #1
Opened 2022-12-09 21:16 UTC by ekmb

Signed-off-by: ekmb <ebakhturina@nvidia.com>

2022-12-13 17:05 UTC, yzhang123 requested changes

2022-12-13 23:12 UTC, ekmb commented on nemo_text_processing/text_normalization/normalize_with_audio.py
> +                    pdb.set_trace()
done

2022-12-13 23:12 UTC, ekmb commented on tests/nemo_text_processing/en/test_normalization_with_audio.py
> +                assert test_input == "!!!", f"failing for |{test_input}|"
removed

2022-12-14 16:59 UTC, yzhang123 approved these changes

2022-12-14 16:59 UTC, merged