Adding Kinyarwanda TN, including cardinals, time, abbreviations and t…
NVIDIA/NeMo-text-processing pull request #176
Opened 2024-05-27 00:26 UTC by kurt0cougar

…ransliteration semiotic classes

# What does this PR do ?

Add a one line overview of what this PR aims to accomplish.

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Have you signed your commits? Use ``git commit -s`` to sign.
- [ ] Do all unittests finish successfully before sending PR?
   1) ``pytest`` or (if your machine does not have GPU) ``pytest --cpu`` from the root folder (given you marked your test cases accordingly `@pytest.mark.run_only_on('CPU')`).
   2) Sparrowhawk tests ``bash tools/text_processing_deployment/export_grammars.sh --MODE=test ...``
- [ ] If you are adding a new feature: Have you added test cases for both `pytest` and Sparrowhawk [here](tests/nemo_text_processing).
- [ ] Have you added ``__init__.py`` for every folder and subfolder, including `data` folder which has .TSV files?
- [ ] Have you followed codeQL results and removed unused variables and imports (report is at the bottom of the PR in github review box) ?
- [ ] Have you added the correct license header `Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.` to all newly added Python files?
- [ ] If you copied [nemo_text_processing/text_normalization/en/graph_utils.py](nemo_text_processing/text_normalization/en/graph_utils.py) your header's second line should be `Copyright 2015 and onwards Google, Inc.`. See an example [here](https://github.com/NVIDIA/NeMo-text-processing/blob/main/nemo_text_processing/text_normalization/en/graph_utils.py#L2).
- [ ] Remove import guards (`try import: ... except: ...`) if not already done.
- [ ] If you added a new language or a new feature please update the [NeMo documentation](https://github.com/NVIDIA/NeMo/blob/main/docs/source/nlp/text_normalization/wfst/wfst_text_normalization.rst) (lives in different repo).
- [ ] Have you added your language support to [tools/text_processing_deployment/pynini_export.py](tools/text_processing_deployment/pynini_export.py).
  

**PR Type**:
- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation
- [ ] Test

If you haven't finished some of the above items you can still open "Draft" PR.

2024-06-04 20:32 UTC, tbartley94 commented
@kurt0cougar Implementation question: what's the rational for keeping the cardinals as a separate file. Does reading from file improve graph construction speed that much?

2024-06-04 20:34 UTC, tbartley94 commented
@elenaltz Do we have a format for shared copyright headers?

2024-06-04 21:13 UTC, ekmb commented
> @elenaltz Do we have a format for shared copyright headers?

@tbartley94 do you mean something like this https://github.com/NVIDIA/NeMo-text-processing/blob/main/nemo_text_processing/hybrid/mlm_scorer.py

2024-06-04 21:19 UTC, tbartley94 requested changes
Added comments. Please update all headers to 2024 and include copyright mention for Digital Umuganda (both so y'all are properly accredited and so the MIT license is valid for OSS). Also please add tests for Words to make sure the model is properly processing non-normalizable texts.

2024-06-04 21:19 UTC, tbartley94 commented on nemo_text_processing/text_normalization/rw/verbalizers/time.py
> +        hour = (pynutil.delete("hours:")+delete_space+pynutil.delete("\"")+pynini.closure(NEMO_CHAR,1,60)+pynutil.delete("\"")+delete_space+pynutil.delete("minutes:")+delete_space+pynutil.delete("\""
can you break this up over several lines? difficult to read

2024-06-04 21:19 UTC, tbartley94 commented on tests/nemo_text_processing/rw/test_sparrowhawk_normalization.sh
> +
Create a test for `TNWord` (helps catch overproductivity)

2024-06-20 13:08 UTC, tbartley94 commented
@kurt0cougar Any questions on comments?

2024-06-26 13:46 UTC, kurt0cougar commented on tests/nemo_text_processing/rw/data_text_normalization/test_cases_cardinal.txt
> +1~rimwe
I will include them, thanks

2024-06-26 13:47 UTC, kurt0cougar commented on tools/text_processing_deployment/export_grammars.sh
> +GRAMMARS="tn_grammars" # tn_grammars
Noted.

2024-06-26 13:48 UTC, kurt0cougar commented on nemo_text_processing/text_normalization/rw/taggers/cardinal.py
> +                "20": "makumyabiri",
No, it is never used. But I believe it is used in Kirundi.

2024-07-15 02:13 UTC, tbartley94 commented on tests/nemo_text_processing/rw/test_cardinal.py
> +# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
2024 and Add Copyrights for Digital Umuganda (or parent org..if applicable)

2024-07-15 02:13 UTC, tbartley94 commented on tests/nemo_text_processing/rw/test_time.py
> +# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
2024 and Add Copyrights for Digital Umuganda (or parent org..if applicable)

2024-07-15 02:13 UTC, tbartley94 commented on tests/nemo_text_processing/rw/test_whitelist.py
> +# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
2024 and Add Copyrights for Digital Umuganda (or parent org..if applicable)

2024-07-15 02:14 UTC, tbartley94 commented on nemo_text_processing/text_normalization/rw/data/__init__.py
> +#
2024 and Add Copyrights for Digital Umuganda (or parent org..if applicable)

2024-07-15 02:14 UTC, tbartley94 commented on nemo_text_processing/text_normalization/rw/__init__.py
> +#
2024 and Add Copyrights for Digital Umuganda (or parent org..if applicable)

2024-07-15 02:14 UTC, tbartley94 commented on nemo_text_processing/text_normalization/rw/data/cardinals/__init__.py
> +#
2024 and Add Copyrights for Digital Umuganda (or parent org..if applicable)

2024-07-15 02:15 UTC, tbartley94 commented
@kurt0cougar Any update on this or are you waiting on me to do a review? (Apologies if latter, got swamped.)

2024-07-15 02:16 UTC, tbartley94 commented on nemo_text_processing/text_normalization/rw/taggers/cardinal.py
> +                "20": "makumyabiri",
If it's only found in the other language then nevermind.

2024-07-18 09:34 UTC, kurt0cougar commented
> @kurt0cougar Any update on this or are you waiting on me to do a review? (Apologies if latter, got swamped.)
I am almost done. pytest results and Sparrowhawk tests are not generating the same results on cardinals, I am working on fixing this.

2024-07-18 17:23 UTC, tbartley94 commented
> > @kurt0cougar Any update on this or are you waiting on me to do a review? (Apologies if latter, got swamped.)
> 
> I am almost done. pytest results and Sparrowhawk tests are not generating the same results on cardinals, I am working on fixing this.

Sounds good, feel free to let us know if we can help.

2024-08-14 18:27 UTC, tbartley94 commented
@kurt0cougar Is this ready for another review pass or still working on pushes?

2024-08-16 11:20 UTC, kurt0cougar commented
> @kurt0cougar Is this ready for another review pass or still working on pushes?

Still working on pushes, it seems like I have some conflicts to solve.

2024-08-19 04:35 UTC, closed without merging